services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend:/app

    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend:/app
      - ./model-cache:/opt/model-cache

    command:
      - sh
      - -c
      - python scripts/prefetch_models.py all && python scripts/seed_users.py && uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

    environment:
      PYTHONUNBUFFERED: "1"
      TRANSLATION_BACKEND: nllb
      HF_TOKEN:
      TTS_API_URL: http://tts-service:8001/generate_tts
      WHISPER_DEVICE: cpu
      WHISPER_MODEL: small
      DATABASE_URL: "postgresql://ai_video:ai_video@db:5432/ai_video"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      MAIL_FROM: ${MAIL_FROM}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}

  tts-service:
    build:
      context: ./tts_service
      dockerfile: Dockerfile.tts

    environment:
      COQUI_TOS_AGREED: "1"
      PYTHONUNBUFFERED: "1"

    volumes:
      - ./backend/uploads:/app/uploads
      - ./tts-model-cache:/root/.local/share/tts

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ai_video
      POSTGRES_PASSWORD: ai_video
      POSTGRES_USER: ai_video

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest

    command:
      - server
      - /data
      - --console-address
      - :9001

    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data


volumes:
  postgres_data:
  minio_data: