export interface StorageFileItem {
  id: string;
  filename: string;
  projectName: string;
  resourceType: "source_video" | "dubbed_video" | "audio_track" | "subtitles_docs" | "pipeline_cache";
  sizeBytes: number;
  sizeFormatted: string;
  specs: string;
  createdAt: string;
  status: "ready" | "processing" | "failed";
}

export interface ProjectStorageItem {
  projectName: string;
  storageGB: number;
  percentage: number;
  videoCount: number;
}

export interface ResourceTypeStorageItem {
  key: "source_video" | "dubbed_video" | "audio_track" | "subtitles_docs" | "pipeline_cache";
  label: string;
  dbField: string;
  sizeGB: number;
  percentage: number;
  color: string;
}

export interface InvoiceItem {
  id: string;
  number: string;
  date: string;
  amount: string;
  status: "paid" | "pending" | "failed";
  plan: string;
  downloadUrl?: string;
}

export interface PaymentCard {
  id: string;
  brand: "visa" | "mastercard" | "amex";
  last4: string;
  expiry: string;
  isDefault: boolean;
  holderName: string;
}

export interface ApiKeyItem {
  id: string;
  name: string;
  prefix: string;
  createdDate: string;
  lastUsed: string;
  environment: "production" | "development";
}

export interface ActiveSession {
  id: string;
  device: string;
  browser: string;
  location: string;
  ipAddress: string;
  lastActive: string;
  isCurrent: boolean;
  iconType: "desktop" | "mobile" | "tablet";
}

export interface SecurityAuditItem {
  id: string;
  action: string;
  location: string;
  ipAddress: string;
  timestamp: string;
  status: "success" | "warning" | "failed";
}

export interface IntegrationApp {
  id: string;
  name: string;
  category: "storage" | "ai" | "productivity";
  description: string;
  connected: boolean;
  accountEmail?: string;
  iconName: string;
  badge?: string;
}

export interface VoiceProfile {
  id: string;
  name: string;
  gender: "female" | "male" | "neutral";
  accent: string;
  recommendedTone?: string;
  provider: "xtts_v2" | "elevenlabs" | "azure_neural" | "qwen3_tts";
}

export const INITIAL_MOCK_SETTINGS = {
  // --- GENERAL ---
  general: {
    bio: "AI video localization specialist and media producer.",
    timezone: "UTC+07:00 (Indochina Time - Bangkok, Hanoi, Jakarta)",
    dateFormat: "DD/MM/YYYY",
    numberFormat: "1,234.56",
    firstDayOfWeek: "monday",
    interfaceDensity: "comfortable" as "comfortable" | "compact",
    reducedMotion: false,
  },

  // --- WORKSPACE ---
  workspace: {
    name: "VidNova Creative Studio",
    slug: "vidnova-creative-studio",
    defaultExportResolution: "1080p",
    defaultAspectRatio: "16:9",
    defaultLayout: "grid" as "grid" | "table",
    defaultSorting: "recent",
    autoSave: true,
    showTranscripts: true,
    aiSuggestions: true,
    compactView: false,
    autoPlayHover: true,
    defaultMemberRole: "editor" as "viewer" | "commenter" | "editor" | "admin",
  },

  // --- AI & PROCESSING (Aligned with database ai_models & video_pipeline_configs) ---
  ai: {
    separationModel: "demucs_v4",
    sttModel: "whisperx_large_v3",
    diarizationModel: "pyannote_3.1",
    translationModel: "nllb_200_1.3b",
    ttsModel: "xtts_v2",
    llmModel: "gpt_4o",
    embeddingModel: "qwen3_embedding",
    processingPriority: "balanced" as "speed" | "balanced" | "quality",
    concurrencyLimit: 3, // Pro plan default limit
    gpuAcceleration: true,
    enableNoiseReduction: true,
    enableAudioNormalization: true,
    enableVocalIsolation: true,
    enableFillerWordRemoval: false,
    autoGenerateSubtitles: true,
    autoGenerateDubbing: true,
    autoChapterDetection: true,
    autoGenerateSummary: true,
  },

  // --- TRANSLATION & VOICE ---
  translationVoice: {
    defaultSourceLanguage: "auto",
    defaultTargetLanguage: "vi",
    translationStyle: "natural" as "formal" | "natural" | "creative" | "technical",
    preserveFormatting: true,
    glossaryPreservation: true,
    timestampSync: true,
    selectedVoiceId: "voice-1",
    voiceSpeed: 1.0,
    voicePitch: 0,
    voiceEmotion: "natural" as "natural" | "energetic" | "serious" | "friendly",
    autoDubbing: true,
    subtitleFormat: "srt" as "srt" | "vtt" | "ass",
    subtitleFont: "Inter",
    subtitleFontSize: 18,
    subtitleColor: "#FFFFFF",
    subtitlePosition: "bottom" as "bottom" | "top" | "center",
    maxCharsPerLine: 42,
  },

  // --- BILLING & SUBSCRIPTION (Aligned with database plans & plan_resources) ---
  billing: {
    planCode: "pro",
    planName: "VidNova Pro",
    status: "active" as "active" | "cancelled" | "past_due",
    billingCycle: "monthly" as "monthly" | "yearly",
    priceMonthly: 12.00,
    priceYearly: 120.00,
    renewalDate: "Sep 27, 2026",
    effectiveQuota: {
      storage: {
        totalGB: 100.0,
        usedGB: 72.4,
        usagePercent: 72.4,
      },
      credits: {
        totalCredits: 10000,
        usedCredits: 6420,
        remainingCredits: 3580,
        convertedMinutesTotal: 1000,
        convertedMinutesUsed: 642,
        convertedMinutesRemaining: 358,
      },
      limits: {
        maxUploadResolution: "4K",
        maxExportResolution: "1080p",
        maxConcurrentJobs: 3,
        maxProjects: 50,
      },
    },
    paymentCards: [
      {
        id: "card-1",
        brand: "visa",
        last4: "4242",
        expiry: "08/28",
        isDefault: true,
        holderName: "Alex Morgan",
      },
      {
        id: "card-2",
        brand: "mastercard",
        last4: "8891",
        expiry: "12/27",
        isDefault: false,
        holderName: "Alex Morgan",
      },
    ] as PaymentCard[],
    invoices: [
      {
        id: "inv-1",
        number: "INV-2026-0801",
        date: "Aug 01, 2026",
        amount: "$12.00",
        status: "paid",
        plan: "VidNova Pro (Monthly)",
      },
      {
        id: "inv-2",
        number: "INV-2026-0701",
        date: "Jul 01, 2026",
        amount: "$12.00",
        status: "paid",
        plan: "VidNova Pro (Monthly)",
      },
      {
        id: "inv-3",
        number: "INV-2026-0601",
        date: "Jun 01, 2026",
        amount: "$12.00",
        status: "paid",
        plan: "VidNova Pro (Monthly)",
      },
    ] as InvoiceItem[],
  },

  // --- NOTIFICATIONS (Aligned with database user_notification_preferences) ---
  notifications: {
    // Email Channels
    emailOnPipelineSuccess: true,
    emailOnPipelineFailed: true,
    emailOnQuotaWarning: true,
    emailOnProjectInvitation: true,
    emailOnCommentMention: true,

    // In-App Channels
    inappOnPipelineSuccess: true,
    inappOnPipelineFailed: true,
    inappOnQuotaWarning: true,
    inappOnProjectInvitation: true,
    inappOnCommentMention: true,

    // System/General
    productUpdates: true,
    weeklyDigest: false,
    browserPush: false,
  },

  // --- INTEGRATIONS ---
  integrations: {
    apps: [
      {
        id: "gdrive",
        name: "Google Drive",
        category: "storage",
        description: "Direct import and export projects from your Google Drive storage.",
        connected: true,
        accountEmail: "alex.morgan@vidnova.ai",
        iconName: "hard-drive",
        badge: "Connected",
      },
      {
        id: "dropbox",
        name: "Dropbox",
        category: "storage",
        description: "Seamlessly synchronize completed video translations with Dropbox folders.",
        connected: false,
        iconName: "box",
      },
      {
        id: "s3",
        name: "AWS S3 / Cloudflare R2",
        category: "storage",
        description: "Connect enterprise object storage bucket for automated media backups.",
        connected: false,
        iconName: "database",
      },
      {
        id: "elevenlabs",
        name: "ElevenLabs Voice API",
        category: "ai",
        description: "Access custom ElevenLabs multilingual voice clones and low-latency synthesis.",
        connected: true,
        accountEmail: "Production Voice API Key",
        iconName: "mic",
        badge: "Active",
      },
      {
        id: "openai",
        name: "OpenAI GPT & Whisper API",
        category: "ai",
        description: "Access latest OpenAI models using your organization's API quota.",
        connected: false,
        iconName: "cpu",
      },
      {
        id: "slack",
        name: "Slack Notifications",
        category: "productivity",
        description: "Receive channel notifications when team video translations complete.",
        connected: true,
        accountEmail: "#video-production channel",
        iconName: "message-square",
        badge: "Channel #video",
      },
      {
        id: "discord",
        name: "Discord Webhook",
        category: "productivity",
        description: "Post automated pipeline status updates into community channels.",
        connected: false,
        iconName: "radio",
      },
    ] as IntegrationApp[],
    apiKeys: [
      {
        id: "key-1",
        name: "Production Pipeline Worker",
        prefix: "vn_live_9a8f",
        createdDate: "Aug 10, 2026",
        lastUsed: "5 mins ago",
        environment: "production",
      },
      {
        id: "key-2",
        name: "Staging Test Suite",
        prefix: "vn_test_4c21",
        createdDate: "Jul 22, 2026",
        lastUsed: "Yesterday",
        environment: "development",
      },
    ] as ApiKeyItem[],
  },

  // --- SECURITY (Aligned with database refresh_tokens & activity_logs) ---
  security: {
    twoFactorEnabled: false,
    twoFactorSecret: "VIDNOVA-X79K-2M4Q-99LP",
    passwordLastChanged: "3 months ago",
    activeSessions: [
      {
        id: "sess-1",
        device: "Windows 11 PC (Chrome 128)",
        browser: "Chrome 128.0",
        location: "Ho Chi Minh City, Vietnam",
        ipAddress: "118.69.182.45",
        lastActive: "Active now",
        isCurrent: true,
        iconType: "desktop",
      },
      {
        id: "sess-2",
        device: "iPhone 15 Pro (Safari)",
        browser: "Mobile Safari 17.5",
        location: "Hanoi, Vietnam",
        ipAddress: "14.232.208.19",
        lastActive: "2 hours ago",
        isCurrent: false,
        iconType: "mobile",
      },
      {
        id: "sess-3",
        device: "MacBook Pro M3 (Firefox)",
        browser: "Firefox 129.0",
        location: "Da Nang, Vietnam",
        ipAddress: "113.161.72.10",
        lastActive: "2 days ago",
        isCurrent: false,
        iconType: "desktop",
      },
    ] as ActiveSession[],
    auditLogs: [
      {
        id: "log-1",
        action: "Password updated successfully",
        location: "Ho Chi Minh City, Vietnam",
        ipAddress: "118.69.182.45",
        timestamp: "Aug 26, 2026 14:20",
        status: "success",
      },
      {
        id: "log-2",
        action: "New API Key created (Production Pipeline Worker)",
        location: "Ho Chi Minh City, Vietnam",
        ipAddress: "118.69.182.45",
        timestamp: "Aug 10, 2026 09:15",
        status: "success",
      },
      {
        id: "log-3",
        action: "Sign-in from new mobile device",
        location: "Hanoi, Vietnam",
        ipAddress: "14.232.208.19",
        timestamp: "Aug 02, 2026 19:42",
        status: "warning",
      },
    ] as SecurityAuditItem[],
  },

  // --- DATA & PRIVACY: REAL STORAGE BREAKDOWN & RETENTION ---
  privacy: {
    totalProjectsCount: 28,
    totalVideosCount: 64,
    totalTranscriptsCount: 142,
    aiModelTrainingConsent: false,
    telemetryAnalytics: true,
    personalizedRecommendations: true,
    trashRetentionDays: 30 as 30 | 60 | 90,
    autoCleanCache: true,
    archiveExportStatus: "idle" as "idle" | "generating" | "ready",
    
    // Real Resource Storage Breakdown
    storageByType: [
      {
        key: "source_video",
        label: "Original Source Videos",
        dbField: "videos.original_path",
        sizeGB: 42.5,
        percentage: 58.7,
        color: "var(--color-primary)",
      },
      {
        key: "dubbed_video",
        label: "Rendered Dubbed Videos",
        dbField: "video_render_outputs.output_video_path",
        sizeGB: 18.2,
        percentage: 25.1,
        color: "#3B82F6",
      },
      {
        key: "audio_track",
        label: "Extracted Audio & Vocal Tracks",
        dbField: "videos.extracted_vocal_path, dubbed_audio_path",
        sizeGB: 7.4,
        percentage: 10.2,
        color: "#8B5CF6",
      },
      {
        key: "subtitles_docs",
        label: "Subtitles & Structured Documents",
        dbField: "subtitle_segments, video_documents",
        sizeGB: 1.8,
        percentage: 2.5,
        color: "#EC4899",
      },
      {
        key: "pipeline_cache",
        label: "Temporary Pipeline Cache",
        dbField: "/tmp/ intermediate audio chunks & VAD buffers",
        sizeGB: 2.5,
        percentage: 3.5,
        color: "#94A3B8",
      },
    ] as ResourceTypeStorageItem[],

    // Storage by Project Distribution
    storageByProject: [
      {
        projectName: "Marketing Campaign 2026",
        storageGB: 28.4,
        percentage: 39.2,
        videoCount: 14,
      },
      {
        projectName: "YouTube AI Tech Series",
        storageGB: 17.2,
        percentage: 23.8,
        videoCount: 22,
      },
      {
        projectName: "Tech Talks & Keynotes",
        storageGB: 14.8,
        percentage: 20.4,
        videoCount: 16,
      },
      {
        projectName: "Studio Localization",
        storageGB: 12.0,
        percentage: 16.6,
        videoCount: 12,
      },
    ] as ProjectStorageItem[],

    // Real Realistic Files List
    storageFiles: [
      {
        id: "file-1",
        filename: "Product_Launch_2026_Master_4K.mp4",
        projectName: "Marketing Campaign 2026",
        resourceType: "dubbed_video",
        sizeBytes: 4509715660,
        sizeFormatted: "4.2 GB",
        specs: "4K • 60fps • 24:15",
        createdAt: "Aug 24, 2026",
        status: "ready",
      },
      {
        id: "file-2",
        filename: "AI_Tech_Keynote_Source_Raw.mp4",
        projectName: "Tech Talks & Keynotes",
        resourceType: "source_video",
        sizeBytes: 3006477107,
        sizeFormatted: "2.8 GB",
        specs: "1080p • 60fps • 45:10",
        createdAt: "Aug 22, 2026",
        status: "ready",
      },
      {
        id: "file-3",
        filename: "Episode_12_Vietnamese_Dubbed.mp4",
        projectName: "YouTube AI Tech Series",
        resourceType: "dubbed_video",
        sizeBytes: 2040109465,
        sizeFormatted: "1.9 GB",
        specs: "1080p • 30fps • 18:30",
        createdAt: "Aug 20, 2026",
        status: "ready",
      },
      {
        id: "file-4",
        filename: "Keynote_Vocal_Stem_Demucs.wav",
        projectName: "Tech Talks & Keynotes",
        resourceType: "audio_track",
        sizeBytes: 912261120,
        sizeFormatted: "870 MB",
        specs: "48kHz 24-bit WAV • 45:10",
        createdAt: "Aug 22, 2026",
        status: "ready",
      },
      {
        id: "file-5",
        filename: "Studio_Interview_Speaker_A.wav",
        projectName: "Studio Localization",
        resourceType: "audio_track",
        sizeBytes: 356515840,
        sizeFormatted: "340 MB",
        specs: "XTTS v2 Voice Clone • 18:30",
        createdAt: "Aug 18, 2026",
        status: "ready",
      },
      {
        id: "file-6",
        filename: "Temp_Chunk_Buffers_Job_9a8f.bin",
        projectName: "Marketing Campaign 2026",
        resourceType: "pipeline_cache",
        sizeBytes: 128974848,
        sizeFormatted: "123 MB",
        specs: "Intermediate VAD Chunks",
        createdAt: "Aug 25, 2026",
        status: "processing",
      },
      {
        id: "file-7",
        filename: "Marketing_Launch_Subtitles_Vi.srt",
        projectName: "Marketing Campaign 2026",
        resourceType: "subtitles_docs",
        sizeBytes: 1887436,
        sizeFormatted: "1.8 MB",
        specs: "SRT • 640 sync segments",
        createdAt: "Aug 24, 2026",
        status: "ready",
      },
      {
        id: "file-8",
        filename: "Video_Summary_Executive_Brief.pdf",
        projectName: "YouTube AI Tech Series",
        resourceType: "subtitles_docs",
        sizeBytes: 1258291,
        sizeFormatted: "1.2 MB",
        specs: "PDF Document • 8 pages",
        createdAt: "Aug 20, 2026",
        status: "ready",
      },
    ] as StorageFileItem[],
  },
};

export const VOICE_PROFILES: VoiceProfile[] = [
  {
    id: "voice-1",
    name: "Aria (Coqui XTTS v2)",
    gender: "female",
    accent: "US English",
    recommendedTone: "Warm & Professional",
    provider: "xtts_v2",
  },
  {
    id: "voice-2",
    name: "Minh Duc (Azure Neural)",
    gender: "male",
    accent: "Vietnamese Northern",
    recommendedTone: "Clear & Storytelling",
    provider: "azure_neural",
  },
  {
    id: "voice-3",
    name: "Mai Linh (Azure Neural)",
    gender: "female",
    accent: "Vietnamese Southern",
    recommendedTone: "Friendly & Expressive",
    provider: "azure_neural",
  },
  {
    id: "voice-4",
    name: "Marcus (ElevenLabs Multilingual v2)",
    gender: "male",
    accent: "UK British",
    recommendedTone: "Authoritative & Documentary",
    provider: "elevenlabs",
  },
  {
    id: "voice-5",
    name: "Yuki (Qwen3-TTS Neural)",
    gender: "female",
    accent: "Tokyo Japanese",
    recommendedTone: "Polite & Narration",
    provider: "qwen3_tts",
  },
];
