import { useState } from "react";
import { Cpu, Zap, Volume2, Sparkles, Mic, Layers, Wand2, Scissors, AudioWaveform } from "lucide-react";
import { useTranslation } from "react-i18next";
import { toast } from "../../../lib/toast";
import SettingCard from "../SettingCard";
import SelectBox from "../SelectBox";
import SettingsSectionHeader from "../common/SettingsSectionHeader";
import SettingsRow from "../common/SettingsRow";
import SettingsSlider from "../common/SettingsSlider";
import SettingsBadge from "../common/SettingsBadge";
import Toggle from "../Toggle";
import { INITIAL_MOCK_SETTINGS } from "../mock/settingsMockData";

export interface AIProcessingSectionProps {
  autoTranslation?: boolean;
  autoSummary?: boolean;
  onAutoTranslationChange?: (val: boolean) => void;
  onAutoSummaryChange?: (val: boolean) => void;
}

export default function AIProcessingSection({
  autoTranslation: propAutoTranslation,
  autoSummary: propAutoSummary,
  onAutoTranslationChange,
  onAutoSummaryChange,
}: AIProcessingSectionProps) {
  const { t } = useTranslation(["settings", "common"]);

  // Models from database ai_models table
  const [separationModel, setSeparationModel] = useState(INITIAL_MOCK_SETTINGS.ai.separationModel);
  const [sttModel, setSttModel] = useState(INITIAL_MOCK_SETTINGS.ai.sttModel);
  const [diarizationModel, setDiarizationModel] = useState(INITIAL_MOCK_SETTINGS.ai.diarizationModel);
  const [translationModel, setTranslationModel] = useState(INITIAL_MOCK_SETTINGS.ai.translationModel);
  const [ttsModel, setTtsModel] = useState(INITIAL_MOCK_SETTINGS.ai.ttsModel);
  const [llmModel, setLlmModel] = useState(INITIAL_MOCK_SETTINGS.ai.llmModel);

  // Compute and priority
  const [priority, setPriority] = useState(INITIAL_MOCK_SETTINGS.ai.processingPriority);
  const [concurrency, setConcurrency] = useState(INITIAL_MOCK_SETTINGS.ai.concurrencyLimit);
  const [gpuAcceleration, setGpuAcceleration] = useState(INITIAL_MOCK_SETTINGS.ai.gpuAcceleration);

  // Audio Filters (video_pipeline_configs)
  const [noiseReduction, setNoiseReduction] = useState(INITIAL_MOCK_SETTINGS.ai.enableNoiseReduction);
  const [normalization, setNormalization] = useState(INITIAL_MOCK_SETTINGS.ai.enableAudioNormalization);
  const [vocalIsolation, setVocalIsolation] = useState(INITIAL_MOCK_SETTINGS.ai.enableVocalIsolation);
  const [fillerWordRemoval, setFillerWordRemoval] = useState(INITIAL_MOCK_SETTINGS.ai.enableFillerWordRemoval);

  // Automations (video_pipeline_configs)
  const [localAutoTranslation, setLocalAutoTranslation] = useState(
    propAutoTranslation ?? INITIAL_MOCK_SETTINGS.ai.autoGenerateDubbing
  );
  const [localAutoSummary, setLocalAutoSummary] = useState(
    propAutoSummary ?? INITIAL_MOCK_SETTINGS.ai.autoGenerateSummary
  );
  const [autoSubtitles, setAutoSubtitles] = useState(INITIAL_MOCK_SETTINGS.ai.autoGenerateSubtitles);
  const [autoChapters, setAutoChapters] = useState(INITIAL_MOCK_SETTINGS.ai.autoChapterDetection);

  const [isSaved, setIsSaved] = useState(true);

  const autoTranslation = propAutoTranslation ?? localAutoTranslation;
  const autoSummary = propAutoSummary ?? localAutoSummary;

  const markDirty = () => setIsSaved(false);

  const handleSave = () => {
    setIsSaved(true);
    toast.success(
      t("settings:toast.settingsSaved", "Settings saved"),
      t("settings:toast.aiSavedDesc", "AI processing engines and parameters updated.")
    );
  };

  const handleReset = () => {
    setSeparationModel("demucs_v4");
    setSttModel("whisperx_large_v3");
    setDiarizationModel("pyannote_3.1");
    setTranslationModel("nllb_200_1.3b");
    setTtsModel("xtts_v2");
    setLlmModel("gpt_4o");
    setPriority("balanced");
    setConcurrency(3);
    setGpuAcceleration(true);
    setNoiseReduction(true);
    setNormalization(true);
    setVocalIsolation(true);
    setFillerWordRemoval(false);
    setAutoSubtitles(true);
    setAutoChapters(true);
    setLocalAutoTranslation(true);
    setLocalAutoSummary(true);
    setIsSaved(true);
    toast.info("Reset to defaults", "AI preferences restored.");
  };

  return (
    <div className="space-y-6">
      <SettingsSectionHeader
        title={t("settings:ai.title", "AI & Processing Settings")}
        subtitle={t(
          "settings:ai.subtitle",
          "Configure foundational AI models, pipeline computing priorities, automations, and audio cleansers."
        )}
        isSaved={isSaved}
        onSave={handleSave}
        onReset={handleReset}
      />

      <div className="grid gap-6 lg:grid-cols-2">
        {/* CARD 1: AI MODELS & ENGINES (Mapped from database ai_models) */}
        <SettingCard
          title={t("settings:ai.modelsTitle", "AI Model Architecture")}
          description="Specialized neural models configured for each step of the video translation pipeline."
        >
          <div className="space-y-4">
            {/* STT Model */}
            <div>
              <div className="mb-1.5 flex items-center justify-between">
                <label className="text-xs font-semibold text-[var(--color-text-secondary)] flex items-center gap-1.5">
                  <Mic size={14} className="text-[var(--color-primary)]" />
                  {t("settings:ai.sttEngine", "Speech-to-Text (STT) Model")}
                </label>
                <SettingsBadge variant="primary" size="sm">
                  WhisperX
                </SettingsBadge>
              </div>
              <SelectBox
                value={sttModel}
                onChange={(val) => {
                  setSttModel(val);
                  markDirty();
                }}
              >
                <option value="whisperx_large_v3">
                  WhisperX Large v3 (Phoneme alignment & VAD) - Default
                </option>
                <option value="whisper_turbo">
                  Whisper Large v3 Turbo (High Speed)
                </option>
                <option value="google_chirp_2">
                  Google Cloud Speech Chirp 2 (Cloud API)
                </option>
              </SelectBox>
            </div>

            {/* Audio Separation Model */}
            <div>
              <label className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-[var(--color-text-secondary)]">
                <Scissors size={14} className="text-[var(--color-primary)]" />
                Vocal & Music Separation Model (Demucs)
              </label>
              <SelectBox
                value={separationModel}
                onChange={(val) => {
                  setSeparationModel(val);
                  markDirty();
                }}
              >
                <option value="demucs_v4">Demucs v4 Hybrid (4-Source Stem Isolation) - Recommended</option>
                <option value="mdx_net_karaoke">MDX-Net Extra Vocal (Acapella / Karaoke Extraction)</option>
              </SelectBox>
            </div>

            {/* Translation Model */}
            <div>
              <label className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-[var(--color-text-secondary)]">
                <Layers size={14} className="text-[var(--color-primary)]" />
                {t("settings:ai.translationEngine", "Translation Model")}
              </label>
              <SelectBox
                value={translationModel}
                onChange={(val) => {
                  setTranslationModel(val);
                  markDirty();
                }}
              >
                <option value="nllb_200_1.3b">Meta NLLB-200 (1.3B) - Local Pipeline Default</option>
                <option value="nllb_200_3.3b">Meta NLLB-200 (3.3B High Fidelity)</option>
                <option value="gpt_4o">OpenAI GPT-4o (Contextual Localization)</option>
                <option value="claude_3.5_sonnet">Anthropic Claude 3.5 Sonnet</option>
                <option value="deepl_pro">DeepL Pro Neural MT</option>
              </SelectBox>
            </div>

            {/* TTS / Voice Cloning Model */}
            <div>
              <label className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-[var(--color-text-secondary)]">
                <Volume2 size={14} className="text-[var(--color-primary)]" />
                TTS & Voice Cloning Synthesis Model
              </label>
              <SelectBox
                value={ttsModel}
                onChange={(val) => {
                  setTtsModel(val);
                  markDirty();
                }}
              >
                <option value="xtts_v2">Coqui XTTS v2 Voice Clone (Zero-Shot VAD) - Default</option>
                <option value="qwen3_tts">Qwen3-TTS Neural Multilingual</option>
                <option value="elevenlabs_multilingual_v2">ElevenLabs Multilingual v2 (Ultra-realistic)</option>
                <option value="azure_neural">Azure Cognitive Speech Neural</option>
              </SelectBox>
            </div>

            {/* Diarization & LLM */}
            <div className="grid grid-cols-2 gap-3 pt-1">
              <div>
                <label className="mb-1.5 block text-xs font-semibold text-[var(--color-text-secondary)]">
                  Speaker Diarization
                </label>
                <SelectBox
                  value={diarizationModel}
                  onChange={(val) => {
                    setDiarizationModel(val);
                    markDirty();
                  }}
                >
                  <option value="pyannote_3.1">Pyannote Audio 3.1</option>
                </SelectBox>
              </div>

              <div>
                <label className="mb-1.5 block text-xs font-semibold text-[var(--color-text-secondary)]">
                  LLM Chapter Generator
                </label>
                <SelectBox
                  value={llmModel}
                  onChange={(val) => {
                    setLlmModel(val);
                    markDirty();
                  }}
                >
                  <option value="gpt_4o">GPT-4o</option>
                  <option value="gpt_4o_mini">GPT-4o Mini</option>
                  <option value="qwen_2.5_72b">Qwen 2.5 72B</option>
                  <option value="deepseek_v3">DeepSeek-V3</option>
                </SelectBox>
              </div>
            </div>
          </div>
        </SettingCard>

        {/* CARD 2: COMPUTE & PROCESSING PRIORITY */}
        <SettingCard
          title={t("settings:ai.computeTitle", "Compute & Processing Priority")}
          description={t(
            "settings:ai.computeDesc",
            "Adjust hardware acceleration, queuing priority, and batch concurrency."
          )}
        >
          <div className="space-y-4">
            <div>
              <label className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-[var(--color-text-secondary)]">
                <Zap size={14} className="text-[var(--color-primary)]" />
                {t("settings:ai.processingPriority", "Processing Priority")}
              </label>
              <SelectBox
                value={priority}
                onChange={(val) => {
                  setPriority(val as any);
                  markDirty();
                }}
              >
                <option value="balanced">Balanced (Optimized throughput & credits)</option>
                <option value="speed">High Speed (Priority dedicated GPU allocation)</option>
                <option value="quality">Maximum Quality (Multi-pass verification)</option>
              </SelectBox>
            </div>

            <SettingsSlider
              label={t("settings:ai.concurrencyLimit", "Parallel Job Concurrency")}
              description="Maximum simultaneous video chunks processed in parallel (Pro tier limit: 3)."
              min={1}
              max={6}
              step={1}
              value={concurrency}
              unit=" Streams"
              onChange={(val) => {
                setConcurrency(val);
                markDirty();
              }}
            />

            <div className="divide-y divide-[var(--color-border)]/60 pt-1">
              <SettingsRow
                icon={<Cpu size={16} />}
                title={t("settings:ai.gpuAccel", "Dedicated GPU Tensor Acceleration")}
                description={t(
                  "settings:ai.gpuAccelDesc",
                  "Use serverless NVIDIA H100/A100 clusters for 4x faster rendering."
                )}
                badge={<SettingsBadge variant="success" size="sm">Active</SettingsBadge>}
              >
                <Toggle
                  checked={gpuAcceleration}
                  onChange={(val) => {
                    setGpuAcceleration(val);
                    markDirty();
                  }}
                />
              </SettingsRow>
            </div>
          </div>
        </SettingCard>

        {/* CARD 3: AUTOMATION RULES (video_pipeline_configs) */}
        <SettingCard
          title={t("settings:ai.automationTitle", "Pipeline Automations")}
          description="Configure which downstream AI tasks are automatically queued on video upload."
        >
          <div className="divide-y divide-[var(--color-border)]/60">
            <SettingsRow
              icon={<Sparkles size={16} />}
              title={t("settings:ai.autoTranslation", "Auto Generate Dubbing & Translation")}
              description="Automatically trigger Whisper STT, NLLB translation, and XTTS dubbing."
            >
              <Toggle
                checked={autoTranslation}
                onChange={(val) => {
                  onAutoTranslationChange ? onAutoTranslationChange(val) : setLocalAutoTranslation(val);
                  markDirty();
                }}
              />
            </SettingsRow>

            <SettingsRow
              icon={<Layers size={16} />}
              title="Auto Generate Subtitles (.SRT / .VTT)"
              description="Automatically compile aligned closed-caption files upon translation completion."
            >
              <Toggle
                checked={autoSubtitles}
                onChange={(val) => {
                  setAutoSubtitles(val);
                  markDirty();
                }}
              />
            </SettingsRow>

            <SettingsRow
              icon={<Wand2 size={16} />}
              title={t("settings:ai.autoSummary", "Auto Summary & Key Takeaways")}
              description="Generate structured executive summary and key points using LLM."
            >
              <Toggle
                checked={autoSummary}
                onChange={(val) => {
                  onAutoSummaryChange ? onAutoSummaryChange(val) : setLocalAutoSummary(val);
                  markDirty();
                }}
              />
            </SettingsRow>

            <SettingsRow
              icon={<AudioWaveform size={16} />}
              title={t("settings:ai.autoChapterDetection", "Auto Chapter & Timeline Marker Detection")}
              description="Timestamp video topic transitions and create timeline chapter markers."
            >
              <Toggle
                checked={autoChapters}
                onChange={(val) => {
                  setAutoChapters(val);
                  markDirty();
                }}
              />
            </SettingsRow>
          </div>
        </SettingCard>

        {/* CARD 4: AUDIO & VOCAL ENHANCEMENT (video_pipeline_configs) */}
        <SettingCard
          title={t("settings:ai.audioEnhanceTitle", "Audio Cleaners & Acoustic Filters")}
          description="Pre-process audio signals to eliminate hums, echo, and noise before dubbing."
        >
          <div className="divide-y divide-[var(--color-border)]/60">
            <SettingsRow
              icon={<Volume2 size={16} />}
              title={t("settings:ai.noiseReduction", "Acoustic Background Noise Reduction")}
              description="Isolate speaker vocal track from room echo, fan hums, and background noise."
            >
              <Toggle
                checked={noiseReduction}
                onChange={(val) => {
                  setNoiseReduction(val);
                  markDirty();
                }}
              />
            </SettingsRow>

            <SettingsRow
              icon={<Sparkles size={16} />}
              title={t("settings:ai.normalization", "EBU R128 Loudness Normalization")}
              description="Standardize dynamic audio range to international broadcast standard (-14 LUFS)."
            >
              <Toggle
                checked={normalization}
                onChange={(val) => {
                  setNormalization(val);
                  markDirty();
                }}
              />
            </SettingsRow>

            <SettingsRow
              icon={<Mic size={16} />}
              title={t("settings:ai.vocalIsolation", "Vocal & Music Stem Isolation (Demucs)")}
              description="Preserve original background music and sound effects while replacing voice."
            >
              <Toggle
                checked={vocalIsolation}
                onChange={(val) => {
                  setVocalIsolation(val);
                  markDirty();
                }}
              />
            </SettingsRow>

            <SettingsRow
              icon={<Wand2 size={16} />}
              title={t("settings:ai.fillerWordRemoval", "AI Filler Word & Hesitation Removal")}
              description="Automatically trim vocal hesitations, 'um', 'uh', and repeated phrases."
            >
              <Toggle
                checked={fillerWordRemoval}
                onChange={(val) => {
                  setFillerWordRemoval(val);
                  markDirty();
                }}
              />
            </SettingsRow>
          </div>
        </SettingCard>
      </div>
    </div>
  );
}
